name: HackReport
main: xyz.acrylicstyle.hackReport.HackReport
version: 0.0.1
softdepend:
  - LuckPerms
depend:
  - TomeitoLib
commands:
  ignore:
    description: "Ignore specific player's chat"
  opchat:
    aliases: "oc"
    permission: hackreport.opchat
  commandlog:
    aliases: ["clog", "cl"]
    permission: hackreport.commandlog
  namechanges:
    description: "shows name changes"
    permission: hackreport.namechanges
