name: HackReport
main: xyz.acrylicstyle.hackReport.HackReport
version: 0.0.1
softdepend:
  - LuckPerms
depend:
  - TomeitoLib
  - JoinChecker
commands:
  report:
    description: "Report a player."
  reports:
    description: "Shows reports list."
    aliases: ["reportlist"]
    permission: hackreport.reports
  player:
    description: "Opens player action GUI."
    aliases: ["playeraction"]
    permission: hackreport.player
  hackreport:
    description: "HackReport root command."
    aliases: "hr"
  ignore:
    description: "Ignore specific player's chat"
  mute:
    description: "Mute a player."
  amute:
    description: "Mute a player, but anonymously."
    aliases: ["muteanonymous", "anonymousmute"]
  opchat:
    aliases: "oc"
    permission: hackreport.opchat
  modchat:
    aliases: "mc"
  commandlog:
    aliases: ["clog", "cl"]
    permission: hackreport.commandlog
  muteall:
    description: "Mutes all server chats. (excludes /tell)"
    permission: hackreport.muteall
  namechanges:
    description: "shows name changes"
  warn:
    description: "warns player"
  playerchecker:
    description: "Gives player a player checker item"
  mutelist:
    permission: hackreport.mutelist
  "/vanish":
    permission: hackreport.vanish
  lookupmute:
    description: ""
permissions:
  hackreport.report:
    description: "allows /report"
    default: true