name: HackReport
main: xyz.acrylicstyle.hackReport.HackReport
version: 0.0.1
softdepend:
  - LuckPerms
depend:
  - TomeitoLib
commands:
  report:
    description: "Report a player."
  reports:
    description: "Shows reports list."
    aliases: ["reportlist"]
    permission: hackreport.reports
  player:
    description: "Opens player action GUI."
    aliases: ["playeraction"]
    permission: hackreport.player
  hackreport:
    description: "HackReport root command."
    aliases: "hr"
  ignore:
    description: "Ignore specific player's chat"
  mute:
    description: "Mute a player."
    permission: hackreport.mute
  opchat:
    aliases: "oc"
    permission: hackreport.opchat
  commandlog:
    aliases: ["clog", "cl"]
    permission: hackreport.commandlog
  muteall:
    description: "Mutes all server chats. (excludes /tell)"
    permission: hackreport.muteall
permissions:
  hackreport.report:
    description: "allows /report"
    default: true